### ISSUE TITLE
About  CADEC

### ISSUE THREAD

**Issue by zlh-source** [daixiangau/acl2020-transition-discontinuous-ner#11]
<img width="527" alt="7919cfe802f40b6131419d9341d68e8" src="https://user-images.githubusercontent.com/50194803/120920283-9ccc0880-c6f0-11eb-91c0-a31d2e64caa4.png">
Hello, there are two versions in the CADEC dataset (as shown in the screenshot), which one do you use?

**Comment by daixiangau** [comment]
CADEC.v2.zip
