### ISSUE TITLE
question about location of downloaded cadec

### ISSUE THREAD

**Issue by 619797944** [daixiangau/acl2020-transition-discontinuous-ner#17]
Hi, could you give me some further information about where I need to locate my cadec file (download from the website) to run the build_data_for_transition_discontinous_ner.sh?
I'm so confused with it because I run it on a MacOS system, but I can not find the output train.txt/dev.txt/test.txt.

**Comment by dainlp** [comment]
when you run extract_annotations.py, you can use --input_ann and --input_text to specify the full path where you save the downloaded folders, for example, python extract_annotations.py --output_filepath /data/dai031/Experiments/CADEC/adr/ann --type_of_interest ADR --log_filepath build_data_for_transition_discontinous_ner.log --input_ann /data/dai031/Corpora/CADEC/cadec/original --input_text /data/dai031/Corpora/CADEC/cadec/text

other python files have similar paramters, for example, --input_dir in tokenization.py
