### ISSUE TITLE
About ShARe dataset 

### ISSUE THREAD

**Issue by xinwei96** [daixiangau/acl2020-transition-discontinuous-ner#4]
Could you point out which databases on this site (https://physionet.org/) you used? Thank you!

**Comment by daixiangau** [comment]
ShAReCLEF eHealth 2013: Natural Language Processing and Information Retrieval for Clinical Care
ShAReCLEF eHealth Evaluation Lab 2014 (Task 2): Disorder Attributes in Clinical Reports
