### ISSUE TITLE
About CADEC named entity types

### ISSUE THREAD

**Issue by LeeSureman** [daixiangau/acl2020-transition-discontinuous-ner#5]
I run ‘data/cadec/build_data_for_transition_discontinuous_ner.sh’  to process CADEC dataset. I find that if only using 'ADR' entity type, the number of entities is 6318 (which is the same with the table1 in your paper). If use all entity type, the number of entities is 9111. So do you use all entity types of CADEC? I'm anxious that I get something wrong when I process CADEC.

**Comment by LeeSureman** [comment]
I use the CADEC.v2

**Comment by daixiangau** [comment]
Hi, we use only ADR. Please see section 4 in our [paper](https://raw.githubusercontent.com/daixiangau/acl2020-transition-discontinuous-ner/master/issue-20201028.PNG).

**Comment by LeeSureman** [comment]
thank you for replying !
