### ISSUE TITLE
About preprocessing ShARe datasets

### ISSUE THREAD

**Issue by LeeSureman** [daixiangau/acl2020-transition-discontinuous-ner#6]
I download two ShARe datasets, And it seems you only provide the script of preprocessing CADEC. So I want to know how I preprocess the ShARe datasets and transform it into the form like your preprocessed CADEC (train, dev and test)

**Comment by daixiangau** [comment]
Hi, please find scripts under data/share2013 folder

**Comment by LeeSureman** [comment]
Thank U~

**Comment by LeeSureman** [comment]
It seems the data/share2013/script.sh is not used to process the original share 2013 form. I don't find 'train/ann' , 'test/Gold_SN2012' etc in original share2013
![65GONRU{{LKY9JC0@UZTJHT](https://user-images.githubusercontent.com/32452367/98501080-29146b00-2289-11eb-8580-a72da781139b.png)

**Comment by daixiangau** [comment]
The train folder corresponds to 'Task1TrainSetCorpus199.zip' and test folder is 'Task1Gold_SN2012'

**Comment by LeeSureman** [comment]
maybe I don't understand, for example, 'train/text' and 'train/ann' both correspond to 'Task1TrainSetCorpus199.zip' ?

**Comment by LeeSureman** [comment]
And I also want to know about preprocessing share2014, thank you ~

**Comment by daixiangau** [comment]
You can unzip Task1TrainSetCorpus199.zip and change the folder name to train.

share 2014 use almost the same code as 2013, I upload the dev.list there.

**Comment by 131250208** [comment]
> maybe I don't understand, for example, 'train/text' and 'train/ann' both correspond to 'Task1TrainSetCorpus199.zip' ?

Hi, I am a newbie for this task. I cannot find how to download the two ShARe datasets by the link provided. Seems it is not called ShARe in the link. Could you tell me what should I type to search for the two datasets? Or could you give me a direct link to the datasets? Thank you!

**Comment by 131250208** [comment]
@LeeSureman Hi, I am a newbie for this task. I cannot find how to download the two ShARe datasets by the link provided. Seems it is not called ShARe in the link. Could you tell me what should I type to search for the two datasets? Or could you give me a direct link to the datasets? Thank you!

**Comment by LeeSureman** [comment]
this is useful to you.
https://github.com/daixiangau/acl2020-transition-discontinuous-ner/issues/4

**Comment by 131250208** [comment]
> this is useful to you.
> #4

Thank you!

**Comment by zlh-source** [comment]
Hello, ShARe datasets needs to submit some applications when downloading, but I don’t know how to fill in one item, can you tell me how to fill it out? Or send this dataset directly to my mailbox 2650603623@qq.com.
Thank you! 
<img width="887" alt="59a5171c4024e91378ec6ed00d0e10c" src="https://user-images.githubusercontent.com/50194803/120918304-65585e80-c6e6-11eb-9510-8e1861f0a4e8.png">

**Comment by daixiangau** [comment]
You mean you don't know how to fill the 'research topic' item? That item asks for a short description of your research project. For example, I was working on clinical information extraction project, and I focus on recognize discontinuous concepts from clinical notes.

**Comment by zlh-source** [comment]
> You mean you don't know how to fill the 'research topic' item? That item asks for a short description of your research project. For example, I was working on clinical information extraction project, and I focus on recognize discontinuous concepts from clinical notes.

There are still problems. This requires me to provide a "reference", but what is the "reference"? 
<img width="868" alt="c967cdfa45d2e0af7bb3a6f1c7f6833" src="https://user-images.githubusercontent.com/50194803/120918882-5f17b180-c6e9-11eb-8011-cd0f8ba912d5.png">

**Comment by daixiangau** [comment]
I guess that warning does not relate to this field; there may be a field asking you to provide contact information about your supervisors or principal investigator (PI) of your research project.

**Comment by zlh-source** [comment]
> I guess that warning does not relate to this field; there may be a field asking you to provide contact information about your supervisors or principal investigator (PI) of your research project.

Thank you, the problem has been resolved.

**Comment by GDUTT1** [comment]
> I download two ShARe datasets, And it seems you only provide the script of preprocessing CADEC. So I want to know how I preprocess the ShARe datasets and transform it into the form like your preprocessed CADEC (train, dev and test)

Hi, I have searched for datasets ShARe 2013 and 2014 for a long time but I couldn't find yet. Could please send me a copy of datasets ShARe 2013 and 2014.  I would appreciate it a lot.

**Comment by daixiangau** [comment]
sorry, i cannot distribute the data, you can download it here: https://physionet.org/content/shareclefehealth2013/1.0/
and https://physionet.org/content/shareclefehealth2014task2/1.0/

you can register as a normal user and then apply for becoming credentialed user.

**Comment by FrankZhao1999** [comment]
> I download two ShARe datasets, And it seems you only provide the script of preprocessing CADEC. So I want to know how I preprocess the ShARe datasets and transform it into the form like your preprocessed CADEC (train, dev and test)

Hi，can u send me a copy of ShARe2013 and ShARe2014， I can't download these datasets directly. I really need to do this experiment at this term. I would be realy grateful if u can send them to me. Thank u very much!!!!
My email address is FrankZhao1999@163.com
